# Branch Protection Rules for main branch
# This file documents the required branch protection settings
# Configure these in GitHub repository settings

# Branch: main
# Protection Rules:
# - Require a pull request before merging
# - Require status checks to pass before merging
# - Require branches to be up to date before merging
# - Require conversation resolution before merging
# - Require signed commits
# - Require linear history
# - Restrict pushes that create files that are larger than 100 MB

# Required Status Checks:
# - Java CI/CD Pipeline (build)
# - Java CI/CD Pipeline (security)
# - Java CI/CD Pipeline (quality-gates)

# Required Reviews:
# - At least 1 approving review
# - Dismiss stale PR approvals when new commits are pushed
# - Require review from code owners

# Restrictions:
# - Restrict pushes to matching branches
# - Allow force pushes: false
# - Allow deletions: false

# Example GitHub CLI command to apply these settings:
# gh api repos/:owner/:repo/branches/main/protection \
#   --method PUT \
#   --field required_status_checks='{"strict":true,"contexts":["Java CI/CD Pipeline (build)","Java CI/CD Pipeline (security)","Java CI/CD Pipeline (quality-gates)"]}' \
#   --field enforce_admins=true \
#   --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true,"require_code_owner_reviews":true}' \
#   --field restrictions='{"users":[],"teams":[]}' \
#   --field required_linear_history=true \
#   --field allow_force_pushes=false \
#   --field allow_deletions=false

# Note: Replace :owner and :repo with your actual GitHub username and repository name
